print ("Hello World!")
print ("Hello Again")
print ("I like typing this.")
print ("This is fun.")
print ('Yay! Printing')
print ("I's much rather you 'not'")
print ('I "said" do not touch this.')
print ("Roosters", 25 + 30 / 6)
